In [ ]:
#DL11 - Loss or Cost Function

In [31]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [32]:
def mae(y_true, y_predicted):
    total_error = 0
    # for loop in two array
    for yt, yp in zip(y_true, y_predicted):
        print(yt, yp)
        total_error += abs(yt-yp)
    print("Total error:", total_error)
    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [33]:
mae(y_true, y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1
Total error: 2.5
MAE: 0.5


0.5

In [34]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [35]:
np.log([0])

/Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [36]:
np.log([0.000000001])

array([-20.72326584])

In [50]:
epsilon = 1e-15

In [51]:
y_predicted

array([1, 1, 0, 0, 1])

In [52]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new
# we have to do becaue log(0) is undefined

[1, 1, 1e-15, 1e-15, 1]

In [53]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [54]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [55]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [56]:
log_loss(y_true, y_predicted)


17.2696280766844